export const subjectData = {
    name: "Lenin Meza",
    titles: ["Software Architect", "Technical Lead", "Full Stack Developer"],
    location: "El Marques, Querétaro, Mexico",
    contact: {
        email: "merolhack@gmail.com",
    },
    social: {
        linkedin: "http://www.linkedin.com/in/leninmezazarco",
        github: "https://github.com/merolhack",
        stackoverflow: "https://stackoverflow.com/users/1006079/lenin-meza",
        devto: "https://dev.to/merolhack",
        credly: "https://www.credly.com/users/lenin-jose-meza-zarco/badges",
    },
    summary:
        "Over 17 years of progressive experience in Web and Enterprise technologies. Extensive, proven background in Bank as a Service (BaaS) infrastructure, complex identity verification platforms, and rigorous enterprise architecture (TOGAF, BIAN). Demonstrated track record in leading high-performance development teams and architecting secure, high-availability cloud systems.",
    competencies: {
        frontend: [
            "Angular (2+, 4, 7)",
            "React",
            "TypeScript",
            "ECMAScript",
            "Bootstrap 4+",
            "HTML5",
            "CSS3",
            "jQuery",
        ],
        backend: [
            "Java (1.8, 17, 21)",
            "Spring Boot (1.5, 2, 3)",
            "NodeJS (Express)",
            "Serverless architectures",
            "PHP (Laravel, Magento)",
        ],
        dataPersistence: [
            "MongoDB",
            "MySQL",
            "SQL Server",
            "Redis",
            "Memcached",
            "Oracle PL/SQL",
        ],
        cloudAndDevOps: [
            "AWS (EC2, S3, EMR)",
            "Google Cloud Platform (GCP)",
            "DigitalOcean",
            "Docker",
            "Kubernetes",
            "GitLab CI/CD",
            "Jenkins",
            "Control-M",
            "OBM (Microfocus)",
            "Dynatrace",
        ],
    },
    experience: [
        {
            role: "Full-Stack Developer VoIP/Gazeti",
            period: "Sep 2025 - Current",
            description: "VoIP architecture on GCP, OpenSIPS configuration, Yeti-switch implementation."
        },
        {
            role: "Software Architect / The Cocktail",
            period: "Sep 2022 - Current",
            description: "Incode Identity Verification implementation, Coppel group onboarding architecture, BIAN/TOGAF standards adherence."
        },
        {
            role: "Senior Consultant at Walmart / Indra",
            period: "Sep 2021 - Sep 2022",
            description: "OBM and Dynatrace monitoring integration, Service Now API scripting via Groovy, network node health scraping."
        },
        {
            role: "Senior Consultant at Sabadell / Indra",
            period: "Nov 2019 - Sep 2021",
            description: "Core Banking system enhancements (Bantotal, GeneXus), BaaS microservices implementation via Spring Boot and Docker/Kubernetes."
        },
        {
            role: "Full Stack Developer at Teamknowlogy",
            period: "Jun 2019 - Nov 2019",
            description: "AWS-based data extractors (Crawlers), Serverless Node.js, Spring Boot REST APIs."
        },
        {
            role: "Technical Lead at Santander",
            period: "Jan 2018 - Jun 2019",
            description: "Digital Factory Spotlight initiatives, BaaS API architecture mapping, Angular SPA frontend development."
        }
    ],
    highlights: {
        github: "Maintainer and contributor to 'mern-stack' repositories demonstrating practical full-stack integrations.",
        stackoverflow: "Extensive authority in deep backend troubleshooting: Redis daemon configurations, MariaDB GSSAPI plugin handling, AWS SMTP port management, and Android WebView Base64 processing.",
        devto: "Authorship and insights regarding MongoDB, Express.JS, React, and NodeJS ecosystem."
    },
    portfolioCreation: {
        title: "How this Portfolio was Created",
        description: "This portfolio is a showcase of Agentic Development. It was autonomously generated by the Google Antigravity Agent using a highly structured 'Master Prompt' dictating an Enterprise AI workflow. The agent was responsible for the full Software Development Lifecycle, including:",
        process: [
            "Bootstrapping Next.js 15+ (App Router) strictly for static export.",
            "Implementing a Vibe Coding design system leveraging Tailwind CSS v4 and Shadcn/ui for a premium 'Deep Dark Mode' enterprise aesthetic.",
            "Structuring an immutable data strategy to bind context programmatically and avoid AI hallucinations.",
            "Auditing layout constraints and scroll-linked Framer Motion micro-animations using a headless Browser Subagent.",
            "Configuring and deploying the final static build autonomously to GitHub Pages via a custom GitHub Actions pipeline."
        ]
    },
    latestRepositories: [
        {
            name: "pressvitals-site-auditor",
            description: "A headless-first WordPress diagnostic engine featuring 22+ proactive probes for performance, security, and DB health — extensible to 48+ via REST API and custom filters.",
            url: "https://github.com/merolhack/pressvitals-site-auditor",
            websiteUrl: "https://wordpress.org/plugins/pressvitals-site-auditor/",
            isPrivate: false
        },
        {
            name: "mach-playbook.github.io",
            description: "Learn MACH fundamentals through concrete service boundaries, clean APIs, and deployment examples, so architecture decisions feel tangible, not theoretical.",
            url: "https://github.com/mach-playbook/mach-playbook.github.io",
            websiteUrl: "https://mach-playbook.github.io/",
            isPrivate: false
        },
        {
            name: "gazeti-healthcheck-scripts",
            description: "Bash scripts for GCP VM and container health check",
            url: "https://github.com/merolhack/gazeti-healthcheck-scripts",
            isPrivate: true
        },
        {
            name: "sbc-derqui-opensips",
            description: "OpenSIPS configuration files for the installation on a Debian 13 On-Premises",
            url: "https://github.com/merolhack/sbc-derqui-opensips",
            isPrivate: true
        },
        {
            name: "oml-daemon-script",
            description: "OMniLeads auto-dialer python script",
            url: "https://github.com/merolhack/oml-daemon-script",
            isPrivate: true
        },
        {
            name: "cpi-visualization-app",
            description: "Next.JS application that connects to Supabase and uses D3.JS as chart library",
            url: "https://github.com/merolhack/cpi-visualization-app",
            isPrivate: false
        },
        {
            name: "oml-config-prod",
            description: "Gazeti OMniLeads Ansible configurations",
            url: "https://github.com/merolhack/oml-config-prod",
            isPrivate: true
        }
    ],
    featuredProject: {
        title: "MACH Playbook",
        subtitle: "A comprehensive guide to building modern, composable architectures.",
        description: "Learn MACH fundamentals through concrete service boundaries, clean APIs, and deployment examples, so architecture decisions feel tangible, not theoretical.",
        url: "https://mach-playbook.github.io/"
    }
};
